# 08 Instructor Lab: Advanced Data Manipulation¶
Author: Mark Lannen  
Course: BGEN632 Grad. Intro. to Python  
Term: Spring 2025

In [3]:
#import Pandas and os library
import pandas as pd
import os

In [7]:
#Set working directory and load the data
os.chdir("/Users/markl1/Documents/Studies/Grad_School-MBA/Spring_2025/Python/week8labs/data")
df = pd.read_csv("github_teams.csv")
df

,name_h,Team_type,Team_size_class,human_members_count,bot_members_count,human_work,work_per_human,human_gini,human_Push,human_IssueComments,human_PRReviewComment,human_MergedPR,bot_work,bot_Push,bot_IssueComments,bot_PRReviewComment,bot_MergedPR,eval_survival_day_median,issues_count
0,_1bqaxzCk0sfQaunsjeViQ/RCEZ3CASdLXbstu9y2JQ7Q,human-bot,Small,2,1,66,33.000000,0.287879,29,33,4,0,43,0,43,0,0,87.0,8.0
1,_9o07rGiC7DFyi-zm91Q0g/VOgMsrjYEwFAq0BY8kHqGQ,human,Small,2,0,62,31.000000,0.467742,62,0,0,0,0,0,0,0,0,NaN,NaN
2,_DzK53uaZXnAX3WcC0W28g/Epc4QWw5PNBQIIdvopEHDA,human,Large,7,0,211,30.142857,0.499661,194,16,1,0,0,0,0,0,0,37.0,46.0
3,_l5u7I5p4thtW5SjR_9_4w/aZNCdVXta7fh7eCMzZP1CA,human-bot,Large,234,12,14579,62.303419,0.738342,1942,11430,1170,37,1972,0,1972,0,0,1.0,4757.0
4,_l5u7I5p4thtW5SjR_9_4w/m_FpD7PKQHqVXHn2bh7u2g,human-bot,Large,38,8,1625,42.763158,0.666607,203,1270,152,0,302,0,302,0,0,2.0,777.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
603,zTj5tlMWgotzJmQl7BP8wQ/iQ914_smScbUO8BI9JlE6A,human-bot,Small,3,1,855,285.000000,0.474854,423,59,373,0,26,0,26,0,0,NaN,NaN
604,zUBexdmYylGGpxiebXm6gg/sJXD2kulWzU35ijdY3SnBQ,human,Small,2,0,63,31.500000,0.436508,63,0,0,0,0,0,0,0,0,NaN,NaN
605,zVSBi-iRKCzLiqFwVt6hbg/8SfUBIOeWUjDoQxeUCX7wQ,human,Medium,5,0,26,5.200000,0.446154,19,5,2,0,0,0,0,0,0,NaN,NaN
606,zVSBi-iRKCzLiqFwVt6hbg/fm_lDWwc8Uu-aZ24BjUNZg,human,Medium,5,0,13,2.600000,0.246154,8,4,1,0,0,0,0,0,0,8.0,10.0
607,ZX09uvu0z_JVPVI-XrPniQ/pxiuGX_R6QI2Euvx2GFIFw,human-bot,Small,2,1,57,28.500000,0.043860,32,24,1,0,8,3,4,1,0,5.0,26.0

In [12]:
#use filter method to return new dataframe with only specified columns
filtered_df = df.filter(items=["Team_type", "human_work", "work_per_human"])
filtered_df

     Team_type  human_work  work_per_human
0    human-bot          66       33.000000
1        human          62       31.000000
2        human         211       30.142857
3    human-bot       14579       62.303419
4    human-bot        1625       42.763158
..         ...         ...             ...
603  human-bot         855      285.000000
604      human          63       31.500000
605      human          26        5.200000
606      human          13        2.600000
607  human-bot          57       28.500000

[608 rows x 3 columns]

In [16]:
#Select columns that end in the letter `t` using the regex `t$`
endin_t_df = df.filter(regex="t$", axis=1)
endin_t_df

,human_members_count,bot_members_count,human_PRReviewComment,bot_PRReviewComment,issues_count
0,2,1,4,0,8.0
1,2,0,0,0,NaN
2,7,0,1,0,46.0
3,234,12,1170,0,4757.0
4,38,8,152,0,777.0
...,...,...,...,...,...
603,3,1,373,0,NaN
604,2,0,0,0,NaN
605,5,0,2,0,NaN
606,5,0,1,0,10.0
607,2,1,1,1,26.0

In [19]:
#Sort your data descending using the columns `Team_size_class`, `human_work`, `work_per_human`
sorted_df = df.sort_values(by=["Team_size_class", "human_work", "work_per_human"], ascending=[False,False,False])
sorted_df

,name_h,Team_type,Team_size_class,human_members_count,bot_members_count,human_work,work_per_human,human_gini,human_Push,human_IssueComments,human_PRReviewComment,human_MergedPR,bot_work,bot_Push,bot_IssueComments,bot_PRReviewComment,bot_MergedPR,eval_survival_day_median,issues_count
559,WLaEz_1Nf-YWzHZa8bBgAA/pLoAhZ1cbPT38VYoSdXGmg,human,Small,3,0,3040,1013.333333,0.292105,434,2606,0,0,0,0,0,0,0,3.0,365.0
209,eIPosZ68E2LjtaixYK65EQ/0Rp6D1ZR1w4YspfD1H-PfA,human-bot,Small,3,1,1639,546.333333,0.413260,1114,283,223,19,156,0,156,0,0,21.0,204.0
410,pxIFRbeuXsUzHtQB3vDwVA/JlkO4fgLE3bD5QjXcU-0CQ,human-bot,Small,3,1,913,304.333333,0.549836,130,507,271,5,53,0,53,0,0,50.0,108.0
268,hXoZRbHPbVxh--funPXSiw/iNU0l_SpKVjGfHOp8vUt8w,human-bot,Small,2,2,910,455.000000,0.065934,207,369,334,0,114,0,114,0,0,4.0,64.0
603,zTj5tlMWgotzJmQl7BP8wQ/iQ914_smScbUO8BI9JlE6A,human-bot,Small,3,1,855,285.000000,0.474854,423,59,373,0,26,0,26,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,7Xep-tc_sXRqdGZ18-MUog/m4gKCZYLclV3PlKDdogc7w,human,Large,9,0,57,6.333333,0.475634,57,0,0,0,0,0,0,0,0,NaN,NaN
564,WMMEJn_D7axJ01w5Xw-8Dw/O8KdDIC1elOLPB08sR2lNw,human-bot,Large,7,1,53,7.571429,0.463612,23,22,8,0,8,2,6,0,0,NaN,NaN
165,bxLD_LudiJ8mO7AZa8QgwQ/9LZ8c1ynzo_ohr4eRwcdcg,human,Large,8,0,51,6.375000,0.517157,51,0,0,0,0,0,0,0,0,NaN,NaN
562,WMMEJn_D7axJ01w5Xw-8Dw/7F60C3mR08-_sYUM_MNHtA,human-bot,Large,7,1,38,5.428571,0.300752,31,6,1,0,11,6,5,0,0,NaN,NaN
292,ilEEnZRNdUqNk7tvvGBo1Q/8xHANrgyHiFV3TuhcqwrpQ,human,Large,8,0,14,1.750000,0.250000,14,0,0,0,0,0,0,0,0,NaN,NaN